loclist = ['mumbai','delhi','agra','goa','patna']
print(loclist[2])
loclist.append('europe')
print(loclist)
loclist.pop()
print(loclist)
loclist.pop(4)
print(loclist)
loclist.insert(0,'kerela')
print(loclist)
loclist.remove('delhi')
print(loclist)
del loclist[2]
print(loclist)
print(sorted(loclist))
print(sorted(loclist,reverse = True))
loclist.reverse()
print(loclist)
loclist.reverse()
print(loclist)
loclist.sort()
print(loclist)
loclist.sort()
print(loclist)